env: flex
# runtime: custom
runtime: gs://elixir-runtime/elixir.yaml
manual_scaling:
  instances: 1
resources:
 cpu: 1
 # .5 is lowest mem
 memory_gb: 0.50
 disk_size_gb: 10
runtime_config:
  release_app: platform_umbrella
  packages:
    - python
    - nodejs-legacy
  build:
    - cd ${PLATFORM_WEB_PATH}/assets && npm install && ./node_modules/webpack/bin/webpack.js -p && cd .. && mix phx.digest
    # - alias elm-make="${ELM_BIN}/elm-make"
    # - elm-make ${ELM_SRC_PATH}/Main.elm --yes --output=${ELM_OUTPUT_PATH}/elm.js
beta_settings:
  cloud_sql_instances: eternal-sunset-206422:us-central1:umbrella-db
env_variables:
  PLATFORM_WEB_PATH: apps/platform_web
  ELM_BIN: apps/platform_web/assets/node_modules/elm/binwrappers
  ELM_OUTPUT_PATH: apps/platform_web/priv/static/js
  ELM_SRC_PATH: apps/platform_web/assets/js/elm/src
  MIX_ENV: prod
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ZQLm3AsToWtXkyePALtGRhjs
  POSTGRES_SOCKET_PATH: /cloudsql/eternal-sunset-206422:us-central1:umbrella-db/.s.PGSQL.5432
