service: platform-umbrella
env: flex
runtime: custom
runtime_config:
  release_app: platform_umbrella
beta_settings:
  cloud_sql_instances: eternal-sunset-206422:us-central1:umbrella-db
env_variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ZQLm3AsToWtXkyePALtGRhjs
  POSTGRES_DATABASE: platform_prod
  POSTGRES_SOCKET_PATH: /cloudsql/eternal-sunset-206422:us-central1:umbrella-db
