env: flex
runtime: custom
runtime_config:
  release_app: platform_umbrella

env_variables:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ZQLm3AsToWtXkyePALtGRhjs
  POSTGRES_SOCKET_PATH: /cloudsql/eternal-sunset-206422:us-central1:platform-umbrella-db/.s.PGSQL.5432
